[build]
  command = "pip install -r requirements.txt && python app.py"
  functions = "netlify/functions"

[build.environment]
  FLASK_ENV = "production"
  DEBUG = "false"
  PYTHON_VERSION = "3.9"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
