services:
  - type: web
    name: gold-forecast
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DEBUG
        value: false
      - key: PORT
        value: 10000
